### ISSUE TITLE
Could not retrieve the list of available versions for provider hashicorp/aws

### ISSUE THREAD

**Issue by stecog** [campaand/terraform-aws-alb-ingress-controller#4]
Hi,
I tried to install this module but have an error when launch `terraform init`:
```
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/aws: no available releases match the given constraints ~> 4.0, >= 5.0.0, 5.9.0
```
Terraform version : 
```
Terraform v1.5.3
on linux_amd64
```

My `main.tf` is:
```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "5.9.0"
    }
  }
...
```
and module have this configuration:
```
module "alb-ingress-controller" {
  source  = "campaand/alb-ingress-controller/aws"
  version = "1.0.1"
...
```
Which version of the aws provider should i use?

Thanks
Stefano

**Comment by campaand** [comment]
Hi @stecog,

the problem is that the constraint applied to the module is ~> 4.0 while you are using, in your root module (`main.tf`), the 5.9.0 version of the terraform provider.
As mentioned at this [link](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#terraform-core-and-provider-versions), using ~> 4.0 forces you to use the major version 4, without limitations for minor and patch versions.

As you can see in your `terraform init` error, you need to respect all the constraint `~> 4.0, >= 5.0.0, 5.9.0`

I will update the module to support also aws provider version 5.

Andrea

**Comment by campaand** [comment]
@stecog resoved in `v2.0.0`
Now you can use version `5.0` and there aren't any constraint for future versions
